---
## NGINX stuff
# Love https://mozilla.github.io/server-side-tls/ssl-config-generator/
cert_location: /etc/ssl/certs/
nginx_sites:
  http:
    -  listen      80 default
    - server_name community.egi.eu
## redirect http to https ##
    - return      301 https://$server_name$request_uri
  https:
     - listen 443 
     - listen [::]:443
     - ssl on
     - ssl_certificate    /etc/ssl/certs/server.crt
     - ssl_certificate_key    /etc/ssl/certs/server.key
     - ssl_session_timeout 1d
     - ssl_protocols TLSv1.2
     - ssl_ciphers  'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
     - ssl_prefer_server_ciphers on
     - ssl_session_cache shared:SSL:10m
     - add_header Strict-Transport-Security max-age=15768000
     - server_name community.egi.eu
     - | 
            location / { 
                proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:; 
                proxy_set_header Host $http_host; proxy_http_version 1.1; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme; 
                }
# Discourse stuff
#discourse_hostname:
developer_emails: 'brucellino@gmail.com'
smtp_address: smtp-relay.gmail.com
# smtp username should be empty for the un-authenticated relay
smtp_username: ""
smtp_port: 587
discourse_plugins:
  - name: Discourse Data Explorer
    description: Allows better querying of Discourse database
    url: https://github.com/discourse/discourse-data-explorer.git
  - name: "Discourse Solved ✔"
    description: "Allows you to mark posts as solutions"
    url: https://github.com/discourse/discourse-solved.git
  - name: Slack plugin
    description: "Discourse to slack plugin"
    url: https://github.com/bernd/discourse-slack-plugin.git
  - name: Checklist
    description: "For when you need to render checklists"
    url: https://github.com/cpradio/discourse-plugin-checklist
  - name: Spreadsheet
    description: "Import google docs spreadsheets to preview them."
    url: https://github.com/tcreativo/plugin_discourse_spreadsheet.git
  - name: OAuth2 provider
    description: "Enable OAuth2 identity provider configuration"
    url: https://github.com/discourse/discourse-oauth2-basic