---
# Kernel from ELrepo
elrepo_kernel: true
elrepo_enablerepo:
   - epel
elrepo_kernel_version: lt
elrepo_repository_elrepo: false
elrepo_repository_kernel: true

# Docker configuration
# to be confirmed if needed and to be installed using packages instead of pip
docker_compose: false
docker_version: "latest"
# https://docs.docker.com/storage/storagedriver/select-storage-driver/
# XXX overlay2 needs either ftype=1 for the XFS partition or using ext4
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.2_release_notes/technology-preview-file_systems
# https://docs.docker.com/storage/storagedriver/device-mapper-driver/
# devicemapper can be used in production, but only with direct-lvm, not loop-lvm
# XXX devicemapper not releasing free space from removed images
# https://github.com/moby/moby/issues/3182
docker_default_config:
  # storage-driver: overlay2
  storage-driver: devicemapper
  log-level: info

# SSH configuration
# For which components (client and server) to generate the configuration for.
# Can be useful when running against a client without an SSH server.
ssh_client_hardening: true
ssh_server_hardening: true
# If true, password login is allowed
ssh_client_password_login: false
ssh_server_password_login: false
# Enable root login with ssh key
ssh_permit_root_login: without-password
# false to disable Agent Forwarding. Set to true to allow Agent Forwarding.
ssh_allow_agent_forwarding: true
# false to disable pam authentication.
ssh_use_pam: true
# false to disable printing of the MOTD
ssh_print_motd: true
# false to disable display of last login information
ssh_print_last_log: true

# NGINX configuration
# Love https://mozilla.github.io/server-side-tls/ssl-config-generator/
cert_location: /etc/ssl/certs/
nginx_sites:
  http:
    - listen      80 default
    - server_name community.egi.eu
    - return      301 https://$server_name$request_uri
  https:
    - listen 443
    - listen [::]:443
    - ssl on
    - ssl_certificate    /etc/ssl/certs/server.crt
    - ssl_certificate_key    /etc/ssl/certs/server.key
    - ssl_session_timeout 1d
    - ssl_protocols TLSv1.2
    - ssl_ciphers  'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
    - ssl_prefer_server_ciphers on
    - ssl_session_cache shared:SSL:10m
    - add_header Strict-Transport-Security max-age=15768000
    - server_name community.egi.eu
    - |
          location / {
              proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:;
              proxy_set_header Host $http_host; proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              }

# Discourse configuration
developer_emails: 'baptiste.grenier@egi.eu'
smtp_address: smtp.mailgun.org
smtp_port: 587
db_shared_buffer_size: 512
unicorn_workers: 4
discourse_hostname: community.egi.eu
# templates to use
# adding web.socketed to allow for multiple ngingx vhost
discourse_templates:
  - postgres
  - redis
  - web
  - sshd
  - web.ratelimited
  - web.socketed
discourse_plugins:
  - name: Assign
    description: "Assign topics to specific people"
    url: https://github.com/discourse/discourse-assign.git
  - name: Cakeday
    description: "Show birthdays and other anniversaries"
    url: https://github.com/discourse/discourse-cakeday
  - name: Canned Responses
    description: "Predefined responses to new topics"
    url: https://github.com/discourse/discourse-canned-replies.git
  - name: Chat plugin
    description: "Discourse to chat plugin"
    url: https://github.com/discourse/discourse-chat-integration.git
  - name: Code Review
    description: "Code Review with github"
    url: https://github.com/discourse/discourse-code-review.git
  - name: Discourse Data Explorer
    description: Allows better querying of Discourse database
    url: https://github.com/discourse/discourse-data-explorer.git
  - name: Events
    description: "Topic event metadata"
    url: https://github.com/angusmcleod/discourse-events.git
  - name: Footnotes
    description: "Allow footnotes in posts"
    url: https://github.com/discourse/discourse-footnote.git
  - name: Graphviz
    description: "Render directed graphs in posts"
    url: https://github.com/discourse/discourse-graphviz
  - name: Locations
    description: "Topic location metadata"
    url: https://github.com/angusmcleod/discourse-locations.git
  - name: OAuth2 provider
    description: "Enable OAuth2 identity provider configuration"
    url: https://github.com/discourse/discourse-oauth2-basic
  - name: Checklist
    description: "For when you need to render checklists"
    url: https://github.com/cpradio/discourse-plugin-checklist
  - name: QnA
    description: "Allow posts to be marked as solutions to questions"
    url: https://github.com/angusmcleod/discourse-question-answer
  - name: "Discourse Solved ✔"
    description: "Allows you to mark posts as solutions"
    url: https://github.com/discourse/discourse-solved.git
  - name: Online
    description: "Show who is online"
    url: https://github.com/davidtaylorhq/discourse-whos-online
  - name: Retort
    description: "Allow different kinds of reactions to topics"
    url: https://github.com/gdpelican/retort.git
    # XXX not deployed?
  - name: Slack plugin
    description: "Discourse to slack plugin"
    url: https://github.com/bernd/discourse-slack-plugin.git
    # XXX not deployed?
  - name: Mailgun plugin for Discourse
    description: Provides a endpoint for Mailgun to deliver inbound emails
    url: https://github.com/halkeye/discourse-mailgun
# XXX not more existing
#  - name: Spreadsheet
#    description: "Import google docs spreadsheets to preview them."
#    url: https://github.com/tcreativo/plugin_discourse_spreadsheet.git
