---
# Love https://mozilla.github.io/server-side-tls/ssl-config-generator/
cert_location: /etc/ssl/certs/
nginx_sites:
 default:
     - listen 443 
     - listen [::]:443
     - return 301 https://$host$request_uri
     - ssl on
     - ssl_certificate    /etc/ssl/certs/server.crt
     - ssl_certificate_key    /etc/ssl/certs/server.key
     - ssl_session_timeout 1d
     - ssl_protocols TLSv1.2
     - ssl_ciphers  'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
     - ssl_prefer_server_ciphers on
     - ssl_session_cache shared:SSL:10m
     - add_header Strict-Transport-Security max-age=15768000
     - server_name community.egi.eu
     - | 
            location / { 
                proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:; 
                proxy_set_header Host $http_host; proxy_http_version 1.1; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme; 
                }