---
cert_location: /etc/ssl/certs/
nginx_sites:
 default:
     - listen 443 
     - listen [::]:443
     - ssl on
     - ssl_certificate    /etc/ssl/certs/server.crt
     - ssl_certificate_key    /etc/ssl/certs/server.key
     - server_name community.egi.eu
     - | 
            location / { 
                proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:; 
                proxy_set_header Host $http_host; proxy_http_version 1.1; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme; 
                }