---
# Ansible playbook to deploy and maintain the EGI community forum
- hosts: forum
  name: harden ssh
  become: true
  tasks:
    - name: Configure remote access
      authorized_key:
        user: root
        key: "{{ item }}"
      loop:
        - 'https://github.com/gwarf.keys'
        - 'https://github.com/enolfc.keys'
  roles:
    - {role: dev-sec.ssh-hardening, tags: ssh}

- hosts: forum
  name: Provide certs
  become: true
  tags:
    - ssl
  tasks:
    - name: Ensure SSL location is present
      file:
        path: "{{ cert_location }}"
        state: directory
        owner: root
        group: root
    - name: Copy Cert Chain
      copy:
        src: etc/ssl/community_egi_eu.crt
        dest: "{{ cert_location }}/server.crt"
        owner: root
        group: root
        mode: u=rw,g=r
    - name: Copy cert key
      copy:
        src: etc/ssl/community_egi_eu.key
        dest: "{{ cert_location }}/server.key"
        owner: root
        group: root
        mode: "u=r"
    - name: sort out firewall
      firewalld:
        service: https
        permanent: yes
        state: enabled
      firewalld:
        service: http
        permanent: yes
        state: enabled
      firewalld:
        service: ssh
        permanent: yes
        state: enabled

# XXX probably not required if not using pip to build python modules
- hosts: forum
  name: Install required packages to build python modules
  become: true
  tasks:
    - name: Install gcc
      package:
        name: gcc
        state: present
    - name: Install python-devel
      package:
        name: python-devel
        state: present

# XXX probably not required, or at least only the kernel-ml not the built files
- hosts: forum
  name: Install a kernel supporting more recent docker drivers
  become: true
  roles:
    - linuxhq.epel
    - linuxhq.elrepo

- hosts: forum
  name: Deploy !
  become: true
  tags:
    - discourse
  vars_files:
    - files/secrets.yml
  roles:
    - {role: EGI-Foundation.discourse-sso, launch: 'False'}
